### ISSUE TITLE
This script seems to only be able to handle nulmages data, can you have him handle nuScenes data?

### ISSUE THREAD

**Issue by JustLiu223** [YksinYoung/Nuscenes_images_to_yolo#1]
This script seems to only be able to handle nulmages data, can you have him handle nuScenes data?

**Comment by YksinYoung** [comment]
Hi. The origin purpose of the scripts was to transfer the nuImages for yolov5, so I just wrote the images part. No further action including handle all nuScenes data as far.
If you're looking for a way to tackle your problem, I suggest checking out the mmdection3d's repo, as I remember they have supported the nuScenes dataset.
Thanks for you words and wish you luck.

**Comment by JustLiu223** [comment]
Okay, thank you very much for your answer
